VSA_MODEL = 'MAP'

NUM_DIMENSIONS = 1000
NUM_FACTORS = 2
NUM_CODEVECTORS = 5


# Test range and step size
MAX_DIMENSIONS = 10000
STEP_DIMENSIONS = 1000
MAX_FACTORS = 10
STEP_FACTORS = 1
MAX_CODEVECTORS = 50
STEP_CODEVECTORS = 5

# Compositional vector noise
NOISE_LEVEL = 0.00

NUM_ITERATIONS = 100
ACTIVATION = 'NONE'